### ISSUE TITLE
concurrent workers

### ISSUE THREAD

**Issue by petschki** [collective/collective.celery#5]
when running more than one worker concurrent only the first one finishes correctly, all others get the following traceback in the celery log:

```
[2015-05-06 16:56:58,119: ERROR/MainProcess] Task collective.celery.calculate_reports[94786072-25c9-408f-8016-7a7ae89546d3] raised unexpected: AttributeError("'function' object has no attribute 'retry'",)
Traceback (most recent call last):
  File "/Users/peterm/.buildout/eggs/celery-3.1.17-py2.7.egg/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/Users/peterm/.buildout/eggs/celery-3.1.17-py2.7.egg/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
  File "/Users/peterm/workspace/yoursri/src/collective.celery/collective/celery/__init__.py", line 33, in new_func
    return runner()
  File "/Users/peterm/workspace/yoursri/src/collective.celery/collective/celery/functionrunner.py", line 64, in __call__
    raise self.new_func.retry(exc=e)
AttributeError: 'function' object has no attribute 'retry'
```

**Comment by MrTango** [comment]
same here with a Redis backend ;)

**Comment by vangheem** [comment]
What version are you on? retries are done with the Retry exception class now.

**Comment by vangheem** [comment]
We could probably use a new release. @ebrehault can you give me access to make releases on pypi?

**Comment by MrTango** [comment]
It works in master, so a new release would be nice ;)

**Comment by vangheem** [comment]
@simonedeponti @ebrehault can you make a new release or give me rights?

**Comment by simonedeponti** [comment]
@vangheem I've made you owner, you should be able to make a release now. Let me know if there are other issues.

**Comment by vangheem** [comment]
@simonedeponti thank you!

released.
